### ISSUE TITLE
Which TestCase should I extend

### ISSUE THREAD

**Issue by j4r3kb** [j6s/phparch#20]
Following code:

```
<?php

namespace Tests\Unit\Architecture;

use J6s\PhpArch\Component\Architecture;
use J6s\PhpArch\PhpArch;
use PHPUnit\Framework\TestCase;

class ArchitectureTest extends TestCase
{
```
works OK, but as I see there is also `J6s\PhpArch\Tests\TestCase;` and

```
<?php

namespace Tests\Unit\Architecture;

use J6s\PhpArch\Component\Architecture;
use J6s\PhpArch\PhpArch;
use J6s\PhpArch\Tests\TestCase;

class ArchitectureTest extends TestCase
{
```

gives me
```
PHP Fatal error:  Uncaught Error: Class 'J6s\PhpArch\Tests\TestCase' not found in /app/tests/Unit/Architecture/ArchitectureTest.php:11
Stack trace:
#0 /app/vendor/bin/.phpunit/phpunit-9.5-0/src/Util/FileLoader.php(65): include_once()
#1 /app/vendor/bin/.phpunit/phpunit-9.5-0/src/Util/FileLoader.php(49): PHPUnit\Util\FileLoader::load('/app/tests/Unit...')
#2 /app/vendor/bin/.phpunit/phpunit-9.5-0/src/Framework/TestSuite.php(402): PHPUnit\Util\FileLoader::checkAndLoad('/app/tests/Unit...')
#3 /app/vendor/bin/.phpunit/phpunit-9.5-0/src/Framework/TestSuite.php(530): PHPUnit\Framework\TestSuite->addTestFile('/app/tests/Unit...')
#4 /app/vendor/bin/.phpunit/phpunit-9.5-0/src/TextUI/TestSuiteMapper.php(67): PHPUnit\Framework\TestSuite->addTestFiles(Array)
#5 /app/vendor/bin/.phpunit/phpunit-9.5-0/src/TextUI/Command.php(389): PHPUnit\TextUI\TestSuiteMapper->map(Object(PHPUnit\TextUI\XmlConfiguration\TestSuiteCollection), '')
#6 /app/vendor/bin/.phpunit/phpunit-9.5-0/src/TextUI/Command.php(110): PHPUnit\TextUI\Command->handleArguments( in /app/vendor/bin/.phpunit/phpunit-9.5-0/src/TextUI/Command.php on line 97
```

Am I doing something wrong here?

**Comment by j6s** [comment]
No, this is working as expected.

For your applications tests, you should extend the PHPUnit `PHPUnit\Framework\TestCase` class as you did in the first example. PHPArch can then be used inside of the test itself. Technically, PHPUnit does not need to be used in PHPUnit - it's just geared towards it.

In your second example, you are extending `J6s\PhpArch\Tests\TestCase`, which is the base class for PHPArch's own tests. They are only autoloadable during library development and are not meant to be used anywhere else.

I hope this clears up the confusion between the two. I guess I could have named the class a bit better to avoid this confusion.
